### ISSUE TITLE
flatpak + flathub submission 

### ISSUE THREAD

**Issue by nobaraos12** [simplex-chat/simplex-chat#1363]
We need an flatpak app to be supported

**Comment by shumvgolove** [comment]
Currently, this is not in a list of priorities. PRs are welcome.

**Comment by nobaraos12** [comment]
also would like to note this would help adoption a little as with an flathub submission it automatically adds itself to their software library across hundreds of laptops & distros

**Comment by x80486** [comment]
There is something I don't fully understand. This is only relevant if/when a desktop application is available. Is that the case for this issue and it was created ahead of time?

**Comment by vladimiry** [comment]
I seem to successfully wrapped it into the flatpak container, but not ready to maintain it in https://github.com/flathub at the moment. So if the core team is ready to maintain it in https://github.com/flathub (so it gets published at https://flathub.org), I could share the tested repo. It's not complex.

**Comment by pm4rcin** [comment]
@vladimiry from the matrix room 

> App image - probably in a month when it’s out of beta. No plans to support flatpack - seems unnecessary tbh.

 But if you could share the tested repo I could check how it works. Maybe I could try to maintain it or at least help with a few things but probably need someone more experienced to guide me initially. :)

**Comment by x80486** [comment]
> App image - probably in a month when it’s out of beta. No plans to support flatpack - seems unnecessary tbh.

`AppImage`s are *forever broken* in rolling releases. It might work for a couple of cycles, then they have no way to keep up with the updates.

Moreover, a security-oriented application that doesn't want to take full advantage of a built-in sandbox doesn't really send the right signal.

**Comment by epoberezkin** [comment]
>  I could share the tested repo.

@vladimiry please share

> App image - probably in a month when it’s out of beta.

It's already available

**Comment by vladimiry** [comment]
> No plans to support flatpack - seems unnecessary tbh.

AppImage seems unnecessary to me for many reasons. Including the fact that it's not connected to a central repository and has worse isolation capabilities than provided by flatpak.

> @vladimiry please share

> But if you could share the tested repo I could check how it works.

Here it's https://github.com/vladimiry-playground/com.github.simplex-chat. I briefly tested it, and it seems to run well, but I'm not familiar with all the functionality to conduct a holistic testing. I put in `readme.md` how to build/run it locally. The app was crashing without `openssl / libffi / libjpeg` libraries, so it got added to the build.

Normally, when the repo is setup and tested, it's pretty easy to update it at https://github.com/flathub. Like just by updating version information and committing it. But it has to be done by someone on a regular manner.

**Comment by Mikaela** [comment]
I hope to see flatpak support as I can trust flatpaks to update and there are tools to manage their permissions such as flatseal.

I have no idea whether the SimpleX Desktop AppImage has even update checking or automatic updates or whether it supports AppImageUpdate and AppImageUpdate apparently doesn't run at all under Wayland and they have no foreseeable future plan of supporting appimages. https://github.com/AppImageCommunity/AppImageUpdate/issues/123#issuecomment-465502261

I know I can `firejail --appimage` SimpleX desktop, but that comes with additional wrapping effort won't answer the concerns on will it ever get updated unless I micromanage it outside of package management.

**Comment by epoberezkin** [comment]
@vladimiry can you make a PR here for what we need for flat hub submission?

**Comment by pm4rcin** [comment]
If we want to build flatpak on this repo it might be worth looking at how OBS guys did it https://github.com/obsproject/obs-studio

**Comment by vladimiry** [comment]
@epoberezkin, how to create app repo at https://github.com/flathub is described in https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md. Specifically in https://docs.flathub.org/docs/for-app-authors/submission/. They prefer the app are controlled by its author. You then replace files in the cloned repo with https://github.com/vladimiry-playground/com.github.simplex-chat, and it most likely should be fine for submitting.

I've updated the https://github.com/vladimiry-playground/com.github.simplex-chat repo to v5.3.0-beta.8, but not to v5.3.0-beta.9, since beta.9 gives the following error on startup:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /tmp/simplex/libs/libapp-lib.so
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at chat.simplex.desktop.MainKt.initHaskell(Main.kt:24)
	at chat.simplex.desktop.MainKt.main(Main.kt:12)
	at chat.simplex.desktop.MainKt.main(Main.kt)
```

**Comment by vladimiry** [comment]
@epoberezkin, by the way, notice that `--filesystem=xdg-download` at https://github.com/vladimiry-playground/com.github.simplex-chat/blob/2be1649efd42bc83a0d8064b9f550db1a803d72c/com.github.simplex-chat.metainfo.yaml#L8C3-L8C30 means that the app has access to "download" folder only at the file system (in addition to the app's folder itself, ie `/home/<usr>/.var/app/com.github.simplex-chat/`).

Many apps prefer `--filesystem=xdg-download` as a sort of safe default, but you can give full access to the `home` if needed, or do something like this:
```
        "--filesystem=xdg-videos:ro",
        "--filesystem=xdg-pictures:ro",
        "--filesystem=xdg-download",
```

So ``--filesystem` setting is something you might want to change before submitting to flathub.

Also, it's possible to override `--filesystem` and other settings by a user using https://flathub.org/apps/com.github.tchx84.Flatseal.

**Comment by vladimiry** [comment]
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /tmp/simplex/libs/libapp-lib.so

v5.3.1 is ok.

**Comment by pm4rcin** [comment]
@vladimiry I have successfully built and tried to use your flatpak without additional modules. Looks like libffi was updated and openssl 3 and libjpeg-turbo are part of freedesktop-sdk. Image preview works for me and sending messages and images too. So one last thing that needs discussion is the `filesystem` permission. There's https://github.com/Wavesonics/compose-multiplatform-file-picker project but I'm not sure if it supports portals. Would be great to check that.

**Comment by vladimiry** [comment]
@pm4rcin thanks for the hint. I can confirm that v5.3.1 works without compiling `openssl / libffi / libjpeg` for use them in runtime.

**Comment by pm4rcin** [comment]
@vladimiry org.freedesktop.Notifications can be removed from manifest since simplex uses sdk 23.08. For info check this [commit](https://gitlab.gnome.org/GNOME/libnotify/-/blob/69aff6e5fa2842e00b409c348bd73188548828b3/NEWS#L25).

**Comment by pm4rcin** [comment]
@epoberezkin
1. There's a name to choose. It should be the following: `chat.simplex.SimpleXChat` although the third element of name could be `SimpleX-Chat` for example or any other variation you see fit.
2. If you want the flatpak manifest to be served **from this repo directly** you'll have to contact flathub for permission because for now most projects manifests are served from flathub github organization's repos (that you can control ofc.). They granted permissions exceptionally for example for Firefox and OBS from the top of my head.

**Comment by pm4rcin** [comment]
@epoberezkin I have updated locally manifest to v5.4.0-beta.2 and there's a problem with calls. It's probably due to flatpak sandbox because it just can't open the browser and be connected to it. I use browsers via flatpak too. The following errors are triggered on accepting call and the app crashes. I guess we have to wait until calls are implemented in simplex itself.
```bash
Exception in thread "DefaultDispatcher-worker-7" java.lang.RuntimeException: Failed to get a new native library instance
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.initMediaPlayerFactory(AudioPlayerComponent.java:88)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.<init>(AudioPlayerComponent.java:61)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.<init>(AudioPlayerComponent.java:83)
	at chat.simplex.common.platform.AudioPlayer$player$2.invoke(RecAndPlay.desktop.kt:28)
	at chat.simplex.common.platform.AudioPlayer$player$2.invoke(RecAndPlay.desktop.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at chat.simplex.common.platform.AudioPlayer.getPlayer(RecAndPlay.desktop.kt:28)
	at chat.simplex.common.platform.AudioPlayer.start(RecAndPlay.desktop.kt:51)
	at chat.simplex.common.platform.AudioPlayer.play(RecAndPlay.desktop.kt:139)
	at chat.simplex.common.platform.SoundPlayer$start$1.invokeSuspend(RecAndPlay.desktop.kt:220)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7fde39b1, Dispatchers.Default]
D: answerIncomingCall iceServers: null
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at org.jetbrains.skiko.Actuals_awtKt.URIHandler_openUri(Actuals.awt.kt:45)
	at org.jetbrains.skiko.URIManager.openUri(Platform.kt:12)
	at chat.simplex.common.views.call.CallView_desktopKt.WebRTCController(CallView.desktop.kt:150)
	at chat.simplex.common.views.call.CallView_desktopKt.ActiveCallView(CallView.desktop.kt:48)
	at chat.simplex.common.AppKt.MainScreen(App.kt:163)
	at chat.simplex.common.AppKt$MainScreen$7.invoke(App.kt)
	at chat.simplex.common.AppKt$MainScreen$7.invoke(App.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2487)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2755)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3386)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3364)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3364)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3329)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:772)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:428)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:269)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:268)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:81)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:54)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:268)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:561)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@284f8eb, androidx.compose.runtime.BroadcastFrameClock@51f5f312, StandaloneCoroutine{Cancelling}@65fc4ee4, FlushCoroutineDispatcher@7c44dd97]
```

**Comment by vladimiry** [comment]
@pm4rcin I use several flatpak apps, and they recently started showing the same issue, after, I guess, some flatpak system dependencies got updated. So it looks like a need to configure something in the flatpak app build process, like adding `portals.conf` file with proper content. There are recent discussions in https://github.com/flatpak/xdg-desktop-portal/issues.

**Comment by x80486** [comment]
Took a shot at this one (https://github.com/x80486/flathub/tree/chat.simplex.app/) because I needed `SimpleX Chat` installed and the `AppImage`...well, it doesn't run in my system.

The issue with `java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!` is [a small bug](https://github.com/JetBrains/skiko/blob/master/skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt#L45) (my opinion) on `Skiko`; I'll file an issue in their repository and see how that goes.

Couple of things before submitting to `Flathub`:

- Generate a proper desktop file — the current one doesn't pass the validation, enforced by `desktop-file-validate` at build time; I created one that's valid with the corresponding values

  ```shell
  x80486@ubuntu-vm:~/Downloads$ cat simplex-desktop-ubuntu-22_04-x86_64/opt/simplex/lib/simplex-simplex.desktop 
  [Desktop Entry]
  Name=simplex
  Comment=simplex
  Exec=/opt/simplex/bin/simplex
  Icon=/opt/simplex/lib/simplex.png
  Terminal=false
  Type=Application
  Categories=Unknown
  MimeType=
  x80486@ubuntu-vm:~/Downloads$ desktop-file-validate simplex-desktop-ubuntu-22_04-x86_64/opt/simplex/lib/simplex-simplex.desktop 
  simplex-desktop-ubuntu-22_04-x86_64/opt/simplex/lib/simplex-simplex.desktop: warning: value "simplex" for key "Comment" in group "Desktop Entry" looks the same as that of key "Name"
  simplex-desktop-ubuntu-22_04-x86_64/opt/simplex/lib/simplex-simplex.desktop: error: value "Unknown" for key "Categories" in group "Desktop Entry" contains an unregistered value "Unknown"; values extending the format should start with "X-"
  simplex-desktop-ubuntu-22_04-x86_64/opt/simplex/lib/simplex-simplex.desktop: hint: value "Unknown" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu

  x80486@ubuntu-vm:~/Downloads$ cd ~/Workshop/flathub/
  x80486@ubuntu-vm:~/Workshop/flathub$ cat chat.simplex.app.desktop 
  [Desktop Entry]
  Categories=Network;InstantMessaging;Chat;
  Exec=simplex-chat
  GenericName=Private and Encrypted Open-Source Messenger
  Icon=chat.simplex.app
  Keywords=audio;chat;encryption;messenger;security;video;
  Name=SimpleX Chat
  StartupNotify=true
  StartupWMClass=simplex-chat
  Terminal=false
  Type=Application
  x80486@ubuntu-vm:~/Workshop/flathub$ desktop-file-validate chat.simplex.app.desktop
  ```
- Would be ideal to bundle the SVG file in the build process so all icons' resolutions are covered — I picked up this one: https://github.com/simplex-chat/website/blob/master/img/icon.svg but not sure what could be the right one
- Would be great to settle on an ID for the application — @vladimiry picked one based on `GitHub`, I picked the one used in `F-Droid`, `Apple Store`, and `Google Play`...but it's not clear what's the one @epoberezkin (and company) might want to use
- Would be ideal to generate the `AppStream MetaInfo` file (e.g.: `chat.simplex.app.metainfo.xml`) as part of the build process, so it's just a matter of placing it in the correct location — I generated one with the correct values, but if it's bundled in the release, much better
- Would be ideal to have the icons and `AppStream MetaInfo` file to follow the application ID, so no need to rename anything — this should be the default for any application in Linux, to be honest, regardless of the final format

There were a few exceptions when receiving audio/video calls and I was able to remove them by using `base: org.videolan.VLC`, but I think that's not needed. Depending on the resolution (or not) for `java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!` it may not be needed.

> And yes, I stole Vladimir's manifest and put some improvements on top :innocent:

**Comment by x80486** [comment]
On the other hand, why `SimpleX Chat` needs to open up a URL in a browser to establish/receive a call? 🧐

I'm not entirely sure how that feature works, but doesn't make sense for me that to do such thing, a new session in a browser is needed :grin:

**Comment by vladimiry** [comment]
> I use several flatpak apps, and they recently started showing the same issue, after, I guess, some flatpak system dependencies got updated

Btw, links clicking in the flatpak apps I use got fixed for me a few days ago, updating flatpak stuff.

**Comment by pm4rcin** [comment]
Today I've tried building and testing 5.7.0 flatpak and when I tried Video or Audio call the GUI was crashing (as soon as I ended call on the other side it worked fine again). Doesn't matter if I initiated call or just tried to accept it crashed. The browser was librewolf installed via flatpak. AppImage call worked fine.
```java
java.lang.RuntimeException: Failed to get a new native library instance
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.initMediaPlayerFactory(AudioPlayerComponent.java:88)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.<init>(AudioPlayerComponent.java:61)
	at uk.co.caprica.vlcj.player.component.AudioPlayerComponent.<init>(AudioPlayerComponent.java:83)
	at chat.simplex.common.platform.AudioPlayer$player$2.invoke(RecAndPlay.desktop.kt:28)
	at chat.simplex.common.platform.AudioPlayer$player$2.invoke(RecAndPlay.desktop.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at chat.simplex.common.platform.AudioPlayer.getPlayer(RecAndPlay.desktop.kt:28)
	at chat.simplex.common.platform.AudioPlayer.start(RecAndPlay.desktop.kt:51)
	at chat.simplex.common.platform.AudioPlayer.play(RecAndPlay.desktop.kt:140)
	at chat.simplex.common.platform.SoundPlayer$start$2.invokeSuspend(RecAndPlay.desktop.kt:220)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$flush$1.invoke(FlushCoroutineDispatcher.skiko.kt:90)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$flush$1.invoke(FlushCoroutineDispatcher.skiko.kt:78)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:99)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.flush(FlushCoroutineDispatcher.skiko.kt:78)
	at androidx.compose.ui.scene.ComposeSceneRecomposer.performScheduledEffects(ComposeSceneRecomposer.skiko.kt:88)
	at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:165)
	at androidx.compose.ui.scene.ComposeSceneMediator$DesktopSkikoView.onRender(ComposeSceneMediator.desktop.kt:523)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.redrawImmediately(LinuxOpenGLRedrawer.kt:83)
	at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.awt.kt:388)
	at androidx.compose.ui.scene.skia.WindowSkiaLayerComponent$contentComponent$1.paint(WindowSkiaLayerComponent.desktop.kt:51)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:434)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:419)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:78)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:76)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:59)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:55)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2304)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:504)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:260)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(UpdateEffect.desktop.kt:55)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:64)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:47)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by anarcat** [comment]
would be great to have a flatpak for this! a few things:

> Generate a proper desktop file — the current one doesn't pass the validation, enforced by desktop-file-validate at build time; I created one that's valid with the corresponding values

in another flatpak i made, i built a "good" desktop file and shipped it directly in the repo until upstream merged it, it worked itself out eventually, as upstream was happy to have a "proper" desktop file anyway... same for icon, appstream data, etc.

in any case, i would suggest sending a PR to flathub already: they'll find a bunch more things for you anyway, and once you hammered all of those down, at least then you have the app shipped and can work on the bugs in that repo...

**Comment by x80486** [comment]
Is there any way this can be moved forward? If it's not quite ready for a full release, perhaps it could be published it in the `beta` area on Flathub. This way, it won’t be widely exposed, but those interested can still find and test it.

However, if the application is functional, even with some minor issues, I see no reason to delay a full Flathub release. The remaining _bugs_ can be handled over time.

@epoberezkin, could you share your thoughts on this?

**Comment by pm4rcin** [comment]
Everything works, it's officially verified. Enjoy :) https://flathub.org/apps/chat.simplex.simplex
