### ISSUE TITLE
Crash at start - address already in use

### ISSUE THREAD

**Issue by alexandrestein** [simplex-chat/simplex-chat#1533]
Hello,

On m'y Pixel 6A with graphen OS it suite common to the app not starting.
OS provides me this message :
`
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.221205.011/2022120700:user/release-keys
package: chat.simplex.app:75
process: chat.simplex.app
processUptime: 80 + 236 ms

java.io.IOException: Address already in use
	at android.net.LocalSocketImpl.bindLocal(Native Method)
	at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:275)
	at android.net.LocalServerSocket.<init>(LocalServerSocket.java:49)
	at chat.simplex.app.SimplexApp$Companion$1.invoke(SimplexApp.kt:176)
	at chat.simplex.app.SimplexApp$Companion$1.invoke(SimplexApp.kt:174)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

`

Any advise?

**Comment by avently** [comment]
Made a PR that should fix the issue. Actually the exception shouldn't happen in current code at all but for some reason it happens. Since I can't reproduce it I hope that the fix is really working in your case. Let me know if you will still have the issue after updating to the newest version (after the PR merge, of course).

**Comment by avently** [comment]
>I'm running the app on multiple accounts on my Graphene OS device.

This was the problem, thanks for sharing. The apps expected only one instance running. Now it's not
