### ISSUE TITLE
[Bug]: Exception in thread "AWT-EventQueue-0" java.net.URISyntaxException: Illegal character in path at index 4: test

### ISSUE THREAD

**Issue by gdmn** [simplex-chat/simplex-chat#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Arch Linux

### App version

AppImage v5.3.0-beta.3 

### Current Behavior

App crashes when joining to group that ends with new line character.

### Expected Behavior

it should not crash, just display an error.

### Steps To Reproduce

1. copy "test\n" (with new line character) to the clipboard
2. join group
3. paste the link
4. error is displayed
5. app crashes
6. i could not start the app anymore :( 
```
./simplex-desktop-x86_64.AppImage 
Segmentation fault (core dumped)
```

### Relevant log output

```shell
Exception in thread "AWT-EventQueue-0" java.net.URISyntaxException: Illegal character in path at index 4: test

	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at chat.simplex.common.views.newchat.PasteToConnectKt$PasteToConnectView$2$1.invoke(PasteToConnect.kt:35)
	at chat.simplex.common.views.newchat.PasteToConnectKt$PasteToConnectView$2$1.invoke(PasteToConnect.kt:33)
	at chat.simplex.common.views.newchat.PasteToConnectKt$PasteToConnectLayout$1$2$3$1.invoke(PasteToConnect.kt:102)
	at chat.simplex.common.views.newchat.PasteToConnectKt$PasteToConnectLayout$1$2$3$1.invoke(PasteToConnect.kt:101)
	at chat.simplex.common.views.helpers.SimpleButtonKt$SimpleButtonFrame$1$modifier$1$1.invoke(SimpleButton.kt:84)
	at chat.simplex.common.views.helpers.SimpleButtonKt$SimpleButtonFrame$1$modifier$1$1.invoke(SimpleButton.kt:84)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:180)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:166)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:258)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:177)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:571)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:459)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:472)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:374)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:289)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:276)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:276)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:276)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:276)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:276)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:156)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:93)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:353)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:346)
	at androidx.compose.ui.ComposeScene.processRelease(ComposeScene.skiko.kt:597)
	at androidx.compose.ui.ComposeScene.processPointerInput(ComposeScene.skiko.kt:573)
	at androidx.compose.ui.ComposeScene.access$processPointerInput(ComposeScene.skiko.kt:93)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:219)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:219)
	at androidx.compose.ui.SyntheticEventSender.sendInternal(SyntheticEventSender.kt:144)
	at androidx.compose.ui.SyntheticEventSender.send(SyntheticEventSender.kt:53)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-WlEVilQ(ComposeScene.skiko.kt:543)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU(ComposeScene.skiko.kt:485)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:468)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:410)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:338)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:331)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:81)
	at androidx.compose.ui.awt.ComposeLayer.onMouseEvent(ComposeLayer.desktop.kt:331)
	at androidx.compose.ui.awt.ComposeLayer.access$onMouseEvent(ComposeLayer.desktop.kt:54)
	at androidx.compose.ui.awt.ComposeLayer$4.mouseReleased(ComposeLayer.desktop.kt:312)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@42631874, androidx.compose.runtime.BroadcastFrameClock@7f00636b, StandaloneCoroutine{Cancelling}@449e81dd, FlushCoroutineDispatcher@443d4093]
```

**Comment by gdmn** [comment]
`./simplex-desktop-x86_64.AppImage` works after system restart. I don't know why. But it doesn't fix the issue with new line character at the end of URL :)

**Comment by numeropi** [comment]
![imagen](https://github.com/simplex-chat/simplex-chat/assets/56868560/36adcb21-f4bb-433c-865c-d61cd63d5957)
I got a similar issue when scrolling up a group chat sin Simplex Desktop client 5.3.2 
Probably somebody uploaded a .mp4 that breaks simplex when reading the filename.

**Comment by jessehorne** [comment]
Can confirm. Got the same issue recently on linux multiplatform after accidentally messing up the URI.
