### ISSUE TITLE
[Q]: How can I firejail the appimage?

### ISSUE THREAD

**Issue by Mikaela** [simplex-chat/simplex-chat#2919]
### Question

As I mentioned in https://github.com/simplex-chat/simplex-chat/issues/1363#issuecomment-1676776400 it's possible to use `firejail` to sandbox the appimage (which I have trust issues towards in general as a platform) and I think the procedure is `firejail --appimage ./simplex.AppImage` e.g.:

```
└┌(%:~)┌- LANG=en firejail --appimage ~/.local/appimages/simplex-desktop-x86_64.AppImage
Reading profile /etc/firejail/min.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 15674, child pid 15676

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Child process initialized in 362.68 ms
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/simplex/libs/libapp-lib.so: /tmp/simplex/libs/libapp-lib.so: failed to map segment from shared object
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at chat.simplex.desktop.MainKt.initHaskell(Main.kt:22)
        at chat.simplex.desktop.MainKt.main(Main.kt:10)
        at chat.simplex.desktop.MainKt.main(Main.kt)

Parent is shutting down, bye...
AppImage detached
```

However as can be seen here, SimpleX desktop isn't working under `firejail` unless I pass `--noprofile` in which case I could as well run it without jailing.

My question is ***has anyone else tried to firejail SimpleX and what is the proper profile for that?***

-----

I originally wanted to open a discussion rather than an issue, but I received the error...

>  You can't perform that action at this time.  

- https://github.com/simplex-chat/simplex-chat/discussions/new

...which I think means the permissions to open discussions have been restricted somehow, likely only to repository collaborators and thus opening an issue is the second best where I found this question template although I don't think firejail is necessarily topical here and I would much rather use previously requested flatpak (https://github.com/simplex-chat/simplex-chat/issues/1363).

*[I am pessimistic towards snap](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491).*

**Comment by rfkat** [comment]
Honestly I'd prefer Flatpak, too: much more widespread than AppImage, and a lot easier to maintain. IMHO preferring AppImage is detrimental, in the long run, because it hampers adoption of SimpleX Chat by relying on a fringe option.
