### ISSUE TITLE
[Bug]: v5.3.0-beta.6 does not start on macOS

### ISSUE THREAD

**Issue by hundehausen** [simplex-chat/simplex-chat#2983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Mac

### OS version

13.5.1 (22G90)

### App version

v5.3.0-beta.6

### Current Behavior

Apple Silicon Mac

After upgrading to the latest beta, the App tries starting, but after 10 seconds nothing happens.

### Expected Behavior

App starts

### Steps To Reproduce

Download latest beta from GitHub (simplex-desktop-macos-aarch64.dmg)
Copy App to Applications
Start it

### Relevant log output

```shell
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/5v/_wq5m5vn01vb0f06jycvgqlw0000gn/T/simplex/libs/libapp-lib.dylib: dlopen(/private/var/folders/5v/_wq5m5vn01vb0f06jycvgqlw0000gn/T/simplex/libs/libapp-lib.dylib, 0x0001): Library not loaded: @rpath/libHSghc-boot-th-9.6.2-ghc9.6.2.dylib
  Referenced from: <A82EF30F-4C63-355C-BF58-381F0A1948C0> /private/var/folders/5v/_wq5m5vn01vb0f06jycvgqlw0000gn/T/simplex/libs/libHStemplate-haskell-2.20.0.0-ghc9.6.2.dylib
  Reason: tried: '/private/var/folders/5v/_wq5m5vn01vb0f06jycvgqlw0000gn/T/simplex/libs/libHSghc-boot-th-9.6.2-ghc9.6.2.dylib' (no such file), '/private/var/folders/5v/_wq5m5vn01vb0f06jycvgqlw0000gn/T/simplex/libs/libHSghc-boot-th-9.6.2-ghc9.6.2.dylib' (no such file), '/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libHSghc-boot-th-9.6.2-ghc9.6.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libHSghc-boot-th-9.6.2-ghc9.6.2.dylib' (no such file), '/Users/evgeny/.ghcup/ghc/9.6.2/lib/ghc-9.6.2/l
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at chat.simplex.desktop.MainKt.initHaskell(Main.kt:22)
	at chat.simplex.desktop.MainKt.main(Main.kt:10)
	at chat.simplex.desktop.MainKt.main(Main.kt)
Failed to launch JVM
```

**Comment by hundehausen** [comment]
[v5.3.0-beta.5](https://github.com/simplex-chat/simplex-chat/releases/tag/v5.3.0-beta.5) works fine

**Comment by mariodian** [comment]
Have the same issue. beta.6 doesn't work, beta.5 works but I had to manually create `~/.local/share/simplex` folder.

**Comment by mabonce** [comment]
I was able to launch the app by finding the missing file in the following folder:

~/.ghcup/ghc/9.6.2/lib/ghc-9.6.2/lib/aarch64-osx-ghc-9.6.2 

I copied it over to my relevant /private/ path as demonstrated from the logs by @hundehausen and trying the app again was successful in launching.

**Comment by epoberezkin** [comment]
can you try the updated dmg please?

**Comment by hundehausen** [comment]
With the updated image, SimpleX is starting again on macOS.
It always takes quite long to start up, that's a bit annoying.

**Comment by epoberezkin** [comment]
> With the updated image, SimpleX is starting again on macOS.

Great - thanks for confirming!

> It always takes quite long to start up, that's a bit annoying.

I think it's only the first time is very long after the upload, as MacOS is validating notarisation with Apple - I see it as well.

The subsequents starts seem faster.
