### ISSUE TITLE
[Bug]: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by dillfrescott** [simplex-chat/simplex-chat#3291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Arch Linux

### App version

5.4-beta-2

### Current Behavior

Trying to open a call leads to the error message popup: `The BROWSE action is not supported on the current platform!` and then when you click okay simplex closes.

### Expected Behavior

It should open the call in the browser. Right?

### Steps To Reproduce

1. Click on call button
2. See error

### Relevant log output

```shell
n/a
```

**Comment by Okkonen-GitHub** [comment]
I am having the same issue, with starting a call, but for me also clicking on a link results in an error (but not a crash)

Here is the log when I click on a link:
```
E: Open url: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at org.jetbrains.skiko.Actuals_awtKt.URIHandler_openUri(Actuals.awt.kt:45)
	at org.jetbrains.skiko.URIManager.openUri(Platform.kt:12)
	at chat.simplex.common.views.chat.item.TextItemViewKt$MarkdownText$2$3.invoke(TextItemView.kt:169)
	at chat.simplex.common.views.chat.item.TextItemViewKt$MarkdownText$2$3.invoke(TextItemView.kt:158)
	at chat.simplex.common.views.chat.item.TextItemViewKt$ClickableText$pressIndicator$1$1$2.invokeSuspend(TextItemView.kt:226)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
And here is what it says when I try to start a call (and after clicking "OK" on the pop-up the program quits):
```
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@17de51a1, androidx.compose.runtime.BroadcastFrameClock@5a17a08e, StandaloneCoroutine{Cancelling}@19c55d06, FlushCoroutineDispatcher@3a1f5fa7]
```
My OS is Artix Linux and I am running Wayland.

**Comment by dillfrescott** [comment]
Im guessing that my tracelogs are probably the same for this issue

**Comment by dillfrescott** [comment]
Yes, my default browser is Edge

**Comment by Okkonen-GitHub** [comment]
Same here, except I'm using firefox. For example running
```sh
xdg-settings get default-web-browser
```
returns "userapp-Firefox-XXDF11.desktop"
And using something like `xdg-open "https://simplex.chat"` works as expected.

**Comment by avently** [comment]
Based on what I read on the Internet, it's Java related problems on Linux. Probably we need to make a workaround for this, like using xdg-open, and copying the link to the clipboard and asking to paste it in the browser in case xdg-open is missing too.
