### ISSUE TITLE
[Bug]: SimplexChat official group invitation returns error

### ISSUE THREAD

**Issue by KamikazeRaven** [simplex-chat/simplex-chat#4128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 13, Android 11

### App version

5.7(200) and 5.6.1(193)

### Current Behavior

I tried to join the SimplexChat official chat group with the invitation link displayed on this github. Here is the [link](https://simplex.chat/invitation/#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3Dsimplex:/contact#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3D)

I first opened the link on desktop and used SimpleXChat version 5.6.1(193) on an Android 11 phone to scan the QR code. It says the code is invalid. Then I tried to add the contact using the link directly. However, it returns below error message:

```
java.net.URISyntaxException: Illegal character in fragment at index 235: https://simplex.chat/invitation/#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3Dsimplex:/contact#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3D
 at java.net.URI$Parser.fail(URI.java:2899)
 at java.net.URI$Parser.checkChars(URI.java:3072)
 at java.net.URI$Parser.parse(URI.java:3118)
 at java.net.URI.<init>(URI.java:584)
 at chat.simplex.common.helpers.ExtensionsKt.toURI(Extensions.kt:20)
 at chat.simplex.app.MainActivityKt.processIntent(MainActivity.kt:149)
 at chat.simplex.app.MainActivity.onNewIntent(MainActivity.kt:55)
 at android.app.Activity.performNewIntent(Activity.java:8358)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1517)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1530)
 at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3821)
 at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3828)
 at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at chat.simplex.app.SimplexApp.onCreate$lambda$0(SimplexApp.kt:53)
 at chat.simplex.app.SimplexApp.$r8$lambda$mrCQa5KReRs3tN4Q90lajT1IiOY(Unknown Source:0)
 at chat.simplex.app.SimplexApp$$ExternalSyntheticLambda0.run(Unknown Source:0)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7918)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I tried the link on another phone with SimpleXChat app version 5.7(200) and Android 13, and I received the same error (or similar error).

### Expected Behavior

The expected behavior should be I joined official SimpleXChat group.

### Steps To Reproduce

1. visit [link](https://simplex.chat/invitation/#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3Dsimplex:/contact#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3D) on desktop web browser.
2. Scan the QR code on a SimpleXChat app on an androind phone (app version 5.6.1 or 5.7, android version 11 or 13)
3. Click the [link](https://simplex.chat/invitation/#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3Dsimplex:/contact#/?v=1&smp=smp%3A%2F%2FPQUV2eL0t7OStZOoAsPEV2QYWt4-xilbakvGUGOItUo%3D%40smp6.simplex.im%2FK1rslx-m5bpXVIdMZg9NLUZ_8JBm8xTt%23MCowBQYDK2VuAyEALDeVe-sG8mRY22LsXlPgiwTNs9dbiLrNuA7f3ZMAJ2w%3D) directly on SimpleXChat app on an android phone (app version 5.6.1 or 5.7, android version 11 or 13).

**Comment by KamikazeRaven** [comment]
Hi @Narasimha-sc , the one I provided came from the "create issue" page. It is on top of the page when trying to create a new issue. Maybe the link was clipped accidently?
