### ISSUE TITLE
General crash report

### ISSUE THREAD

**Issue by d4f5409d** [simplex-chat/simplex-chat#4167]
```kotlin
java.lang.IndexOutOfBoundsException: index (105) is out of bound of [0, 0)
	at androidx.compose.runtime.snapshots.SnapshotStateListKt.validateRange(SnapshotStateList.kt:254)
	at androidx.compose.runtime.snapshots.SnapshotStateListKt.access$validateRange(SnapshotStateList.kt:1)
	at androidx.compose.runtime.snapshots.StateListIterator.next(SnapshotStateList.kt:299)
	at chat.simplex.common.views.chatlist.ChatListNavLinkViewKt.setGroupMembers(ChatListNavLinkView.kt:246)
	at chat.simplex.common.views.chatlist.ChatListNavLinkViewKt$setGroupMembers$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7daded5, java.util.concurrent.Executors$FinalizableDelegatedExecutorService@5d3f6ea]
```

Android 13
v5.7

**Comment by d4f5409d** [comment]
I've used picture in picture.
