### ISSUE TITLE
[Bug]: Error deleting user profile

### ISSUE THREAD

**Issue by Garrett96** [simplex-chat/simplex-chat#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

GrapheneOS - Android 14

### App version

5.7.3

### Current Behavior

I am trying to delete a user profile and server connections along with it, so it does not attempt to sync anymore, and I'm unable to. 

### Expected Behavior

Profile should get deleted!

### Steps To Reproduce

1. Go to `Your chat profiles`.
2. Press-and-hold on a user profile you want to delete.
3. click `Delete`.
4. In `Delete chat profile?` selection menu, select to delete `Profile and server connections`.
5. Error message pops up. [see: relevant log output]

### Relevant log output

```shell
Error deleting user profile

java.lang.Exception: failed to delete the user chatCmdError userId: 1 agent INTERNAL SEUserNotFound 	at chat.simplex.common.model.ChatController.apiDeleteUser(SimpleXAPI.kt:638) 	at chat.simplex.common.model.ChatController$apiDeleteUser$1.invokeSuspend(Unknown Source:16) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by avently** [comment]
Have you tried to relaunch the app? If not, try it. Maybe the problem will go away

**Comment by mattsalves** [comment]
## Troubleshooting Guide: Deleting User Profiles and Server Connections

It seems like there might be an issue with deleting user profiles and their associated server connections in your Android app. The error message indicates that there's an exception occurring during the deletion process, specifically a `SEUserNotFound` error.

### Steps to Fix the Issue:

1. **Verify User Existence**: Ensure that the user profile you are trying to delete actually exists on the server. The `SEUserNotFound` error suggests that the user might not be found on the server, which could be causing the deletion process to fail.

2. **Check Permissions**: Make sure that the app has the necessary permissions to delete user profiles and their associated server connections. Sometimes, permission issues can prevent certain operations from being executed successfully.

**Comment by Narasimha-sc** [comment]
this probably happened because you had a partially deleted profile that did not complete deletion, I think this is fixed for new deletions.
