### ISSUE TITLE
[Bug]: appimage doesn't start after upgrade to f40

### ISSUE THREAD

**Issue by ITwrx** [simplex-chat/simplex-chat#4402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Fedora 40

### App version

5.8.2

### Current Behavior

```
./simplex-desktop-x86_64-5.8.2.AppImage
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/.mount_simpleffkEaK/usr/lib/app/resources/libapp-lib.so: libffi.so.7: cannot open shared object file: No such file or directory

```
My f40 has:
```
/usr/lib/libffi.so.8
/usr/lib/libffi.so.8.1.2
/usr/lib64/libffi.so
/usr/lib64/libffi.so.8
/usr/lib64/libffi.so.8.1.2
```

### Expected Behavior

Progrum starts! :)

### Steps To Reproduce

1) upgrade to f40
2) try to start simpleX appimage
3) experience the fail.

### Relevant log output

```shell
./simplex-desktop-x86_64-5.8.2.AppImage
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/.mount_simpleffkEaK/usr/lib/app/resources/libapp-lib.so: libffi.so.7: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at chat.simplex.desktop.MainKt.initHaskell(Main.kt:37)
	at chat.simplex.desktop.MainKt.main(Main.kt:21)
	at chat.simplex.desktop.MainKt.main(Main.kt)
```

**Comment by ITwrx** [comment]
@Narasimha-sc what does `locate libffi` give you, i wonder? Feel free to just copy the `/usr/lib(64)` locations.
I'm guessing whonix has an older version. Maybe simpleX is specifying `so.7`?

**Comment by tsjk** [comment]
> > @Narasimha-sc what does `locate libffi` give you, i wonder? Feel free to just copy the `/usr/lib(64)` locations. I'm guessing whonix has an older version. Maybe simpleX is specifying `so.7`?
> 
> no command 'locate', I did apt install locate, but then doing locate libffi gives no output (libffi package is installed)

`locate` searches its database, which needs to populated prior to usage.

**Comment by tsjk** [comment]
I actually faced this issue as well when upgrading my appimage from v5.8.0 to v5.8.2. I had libffi 3.2 and libffi 3.4 installed, so I tend to think that perhaps the specification of a certain version is new.
On Gentoo we have a dev-libs/libffi-compat, which also has a 3.3 version. Installing that allows the appimage to start.

**Comment by royborgen** [comment]
I have same issue on Ubuntu 24.04

**Comment by TheFuzzStone** [comment]
Same on EndeavourOS (Arch Linux).
