### ISSUE TITLE
[Bug]: Error when trying to listen to an audio message in the desktop client

### ISSUE THREAD

**Issue by amosstevens** [simplex-chat/simplex-chat#4876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows, Android

### OS version

Android 13, Windows 10 22H2 x64

### App version

6.0.4

### Current Behavior

when i try to listen to an audio message in the desktop client it gives me an error, and it wont reproduce it

### Expected Behavior

it should let me listen the audio message

### Steps To Reproduce

1. connect the mobile to the desktop client
2. listen to an audio message of a direct chat

### Relevant log output

```shell
java.lang.Error: Invalid memory access
	at uk.co.caprica.vlcj.binding.lib.LibVlc.libvlc_event_attach(Native Method)
	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager.addNativeEventListener(NativeEventManager.java:144)
	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager.addEventListener(NativeEventManager.java:118)
	at uk.co.caprica.vlcj.media.EventApi.addMediaEventListener(EventApi.java:41)
	at uk.co.caprica.vlcj.player.base.MediaApi.setPersistentEventListeners(MediaApi.java:460)
	at uk.co.caprica.vlcj.player.base.MediaApi.changeMedia(MediaApi.java:404)
	at uk.co.caprica.vlcj.player.base.MediaApi.prepare(MediaApi.java:85)
	at chat.simplex.common.platform.AudioPlayer.start(RecAndPlay.desktop.kt:51)
	at chat.simplex.common.platform.AudioPlayer.play(RecAndPlay.desktop.kt:140)
	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1$playIfExists$1.invoke(CIVoiceView.kt:65)
	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1$playIfExists$1.invoke(CIVoiceView.kt:63)
	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1$1.invokeSuspend(CIVoiceView.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Narasimha-sc** [comment]
closing as this is very old, please let me know if it still happens
