### ISSUE TITLE
[Bug]: Create Simplex address not working after going past initial setup

### ISSUE THREAD

**Issue by Headedbranch225** [simplex-chat/simplex-chat#5068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

POP_OS 22.04

### App version

6.1.0

### Current Behavior

App crashes when trying to make a simplex address

### Expected Behavior

It creates a simplex address

### Steps To Reproduce

Open app
go past the first screen by connecting mobile
go to this device
click on create simplex address
crash

### Relevant log output

```shell
D: Checking for update
D: useDatabaseKey true
D: sendCmd: apiSetAppFilePaths
D: sendCmd response type cmdOk
D: sendCmd: apiSetEncryptLocalFiles
D: sendCmd response type cmdOk
D: sendCmd: showActiveUser
D: sendCmd response type chatCmdError
D: apiGetActiveUser: chatCmdError chat noActiveUser
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: user: null
D: ChatController startReceiver
D: sendCmd: setLocalDeviceName
D: sendCmd response type cmdOk
D: startChat: started without user
D: Skipping update because of the same version or skipped version
D: sendCmd: listUsers
D: sendCmd response type usersList
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: ModalManager.showPasscodeCustomModal, oneTime: false
D: ModalManager.showPasscodeCustomModal, oneTime: false
D: ModalManager.showCustomModal
D: AlertManager.showAlert
E: App crashed, thread name: AWT-EventQueue-0, exception: java.lang.NullPointerException
	at chat.simplex.common.views.chatlist.ComposableSingletons$UserPickerKt$lambda-2$1.invoke(UserPicker.kt:216)
	at chat.simplex.common.views.chatlist.ComposableSingletons$UserPickerKt$lambda-2$1.invoke(UserPicker.kt:216)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:159)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at chat.simplex.common.views.chatlist.UserPickerKt$UserPicker$6$showCustomModal$1$1$1$1.invoke(UserPicker.kt:151)
	at chat.simplex.common.views.chatlist.UserPickerKt$UserPicker$6$showCustomModal$1$1$1$1.invoke(UserPicker.kt:151)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:137)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at chat.simplex.common.views.helpers.ModalManager$showInView$4$1$1.invoke(ModalView.kt:170)
	at chat.simplex.common.views.helpers.ModalManager$showInView$4$1$1.invoke(ModalView.kt:169)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at chat.simplex.common.views.helpers.ModalManager$showInView$4.invoke(ModalView.kt:167)
	at chat.simplex.common.views.helpers.ModalManager$showInView$4.invoke(ModalView.kt:165)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:137)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:755)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:744)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:818)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:726)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:709)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:768)
	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:141)
	at chat.simplex.common.views.helpers.ModalManager.showInView(ModalView.kt:157)
	at chat.simplex.common.views.helpers.ModalManager$showInView$5.invoke(ModalView.kt)
	at chat.simplex.common.views.helpers.ModalManager$showInView$5.invoke(ModalView.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2557)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2828)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3315)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3266)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:163)
	at androidx.compose.ui.scene.ComposeSceneMediator$DesktopSkikoView.onRender(ComposeSceneMediator.desktop.kt:523)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

D: sendCmd: listUsers
D: sendCmd response type usersList
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
```

**Comment by Headedbranch225** [comment]
This is the log for the flatpak version as it is the one I logged, but it is the same crash (I think) happens on the appimage version

**Comment by Headedbranch225** [comment]
I realised the issue, there should be a check upon address for the presence of a valid user profile on the device

**Comment by AmyNicole8715** [comment]
> I realised the issue, there should be a check upon address for the presence of a valid user profile on the device

Yes! Precisely, actually the same issue with the win 11 version currently: 
I encountered a NullPointerException in the Simplex desktop app, specifically within the UserPicker component. The issue arises in UserPicker.kt at line 222. Here is the stack trace for reference:

`java.lang.NullPointerException
    at chat.simplex.common.views.chatlist.ComposableSingletons$UserPickerKt$lambda-2$1.invoke(UserPicker.kt:222)
    at chat.simplex.common.views.chatlist.ComposableSingletons$UserPickerKt$lambda-2$1.invoke(UserPicker.kt:222)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:159)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at chat.simplex.common.views.chatlist.UserPickerKt$UserPicker$6$showCustomModal$1$1$1$1.invoke(UserPicker.kt:156)
    at chat.simplex.common.views.chatlist.UserPickerKt$UserPicker$6$showCustomModal$1$1$1$1.invoke(UserPicker.kt:156)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:137)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at chat.simplex.common.views.helpers.ModalManager$showInView$4$1$1.invoke(ModalView.kt:183)
    at chat.simplex.common.views.helpers.ModalManager$showInView$4$1$1.invoke(ModalView.kt:182)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
    at chat.simplex.common.views.helpers.ModalManager$showInView$4.invoke(ModalView.kt:182)
    at chat.simplex.common.views.helpers.ModalManager$showInView$4.invoke(ModalView.kt:180)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:137)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:803)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:792)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:771)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:774)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:757)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:816)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:143)
    at chat.simplex.common.views.helpers.ModalManager.showInView(ModalView.kt:172)
    at chat.simplex.common.views.helpers.ModalManager$showInView$5.invoke(ModalView.kt)
    at chat.simplex.common.views.helpers.ModalManager$showInView$5.invoke(ModalView.kt)
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
    at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3552)
    at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
    at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
    at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
    at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
    at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:76)
    at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:168)
    at androidx.compose.ui.scene.ComposeSceneMediator$onRender$1$1.invoke(ComposeSceneMediator.desktop.kt:574)
    at androidx.compose.ui.scene.ComposeSceneMediator$onRender$1$1.invoke(ComposeSceneMediator.desktop.kt:572)
    at androidx.compose.ui.viewinterop.SwingInteropContainer.postponingExecutingScheduledUpdates(SwingInteropContainer.desktop.kt:229)
    at androidx.compose.ui.scene.ComposeSceneMediator.onRender(ComposeSceneMediator.desktop.kt:572)
    at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:533)
    at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
    at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:49)
    at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
    at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
    at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`

OS: Windows 11 Pro, ver. 10.0.22635 Build 22635
Simplex Desktop ver. 6.2.3.0

All that should happen in my opinion is when the user clicks that 2 things need to appear, a don't show this again message that explains how the profile on your phone will not be the same as the one on the desktop app, if you close the app and thus relinquish the connection to our android version on mobile, then the next part should just be a dialog that comes up with "You've created no profile to invite to!"
