### ISSUE TITLE
[Q]: Is the `apiGetChats` from TypeScript correct?

### ISSUE THREAD

**Issue by rdbo** [simplex-chat/simplex-chat#5282]
### Question

An example of what I'm doing currently is:
```ts
const user = await chat.apiGetActiveUser();
// ...
let chats = await chat.apiGetChats(user.userId);
```

In my CLI (6.1.1.0), I get the following log:
```
received command "3" : "/_get chats pcc=off"
```
And the response is:
```js
ChatCommandError: error loading chats
    at _ChatClient.apiGetChats (dist/index.js:589:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async run (dist/index.js:850:5) {
  response: {
    type: 'chatCmdError',
    chatError: {
      type: 'error',
      errorType: { type: 'commandError', message: 'Failed reading: empty' }
    }
  }
}
```

On the other hand, if I do the following:
```ts
let resp = (await chat.sendChatCmdStr("/chats")) as CRApiChats;
```

I get the correct response:
```js
{
  type: 'chats',
  chats: [
    { chatInfo: [Object], chatItems: [Array], chatStats: [Object] },
    { chatInfo: [Object], chatItems: [], chatStats: [Object] },
    { chatInfo: [Object], chatItems: [], chatStats: [Object] },
    { chatInfo: [Object], chatItems: [], chatStats: [Object] }
  ]
}
```

Which makes me think, is there something wrong with `apiGetChats`? Or maybe this is not the intended use for it?
And if it isn't the correct function for this, maybe there should be `apiChats` also?

**Comment by sharifzadesina** [comment]
Any update on this?
