### ISSUE TITLE
[Bug]: Java error when trying to play a voice message

### ISSUE THREAD

**Issue by kaypoush** [simplex-chat/simplex-chat#5379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 13

### App version

6.2

### Current Behavior

When I try to play a 0 second voice message (mistake from the contact), I get the following error message (see log output) and then the play button turns orange.

I'm not sure if it has to be a zero second voice message or not for this error to show up.

### Expected Behavior

There should be no error. Perhaps the app should know that it's failed record and not even send it. When we record a voice message, the send button is too close to the hold to record button which can lead to mistakes. Also when we record there should be a red dot record symbol to make it more clear that it's recording.

### Steps To Reproduce

1. Play a zero second voice message
2. Wait for the error message

### Relevant log output

```shell
java.io.IOException: Prepare failed.: status=0x1 	at android.media.MediaPlayer._prepare(Native Method) 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1309) 	at chat.simplex.common.platform.AudioPlayer.start(RecAndPlay.android.kt:157) 	at chat.simplex.common.platform.AudioPlayer.play(RecAndPlay.android.kt:251) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1$playIfExists$1.invoke(CIVoiceView.kt:66) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1$playIfExists$1.invoke(CIVoiceView.kt:64) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1.invoke(CIVoiceView.kt:76) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$CIVoiceView$1$play$1.invoke(CIVoiceView.kt:63) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$PlayPauseButton$1$1$1.invoke(CIVoiceView.kt:268) 	at chat.simplex.common.views.chat.item.CIVoiceViewKt$PlayPauseButton$1$1$1.invoke(CIVoiceView.kt:268) 	at androidx.compose.foundation.CombinedClickableNodeImpl$clickPointerInput$5.invoke-k-4lQ0M(Clickable.kt:792) 	at androidx.compose.foundation.CombinedClickableNodeImpl$clickPointerInput$5.invoke(Clickable.kt:778) 	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(TapGestureDetector.kt:138) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164) 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470) 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504) 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493) 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364) 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:719) 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:598) 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:620) 	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1044) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:387) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373) 	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:229) 	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:144) 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:120) 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1993) 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1944) 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1828) 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121) 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802) 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121) 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802) 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121) 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802) 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121) 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802) 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500) 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912) 	at android.app.Activity.dispatchTouchEvent(Activity.java:4299) 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458) 	at android.view.View.dispatchPointerEvent(View.java:15309) 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778) 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578) 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034) 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091) 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057) 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222) 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065) 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279) 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038) 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091) 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057) 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065) 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038) 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206) 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157) 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126) 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329) 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267) 	at android.os.MessageQueue.nativePollOnce(Native Method) 	at android.os.MessageQueue.next(MessageQueue.java:335) 	at android.os.Looper.loopOnce(Looper.java:161) 	at android.os.Looper.loop(Looper.java:288) 	at chat.simplex.app.SimplexApp.onCreate$lambda$0(SimplexApp.kt:57) 	at chat.simplex.app.SimplexApp.$r8$lambda$mrCQa5KReRs3tN4Q90lajT1IiOY(Unknown Source:0) 	at chat.simplex.app.SimplexApp$$ExternalSyntheticLambda0.run(Unknown Source:0) 	at android.os.Handler.handleCallback(Handler.java:942) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:201) 	at android.os.Looper.loop(Looper.java:288) 	at android.app.ActivityThread.main(ActivityThread.java:7918) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Narasimha-sc** [comment]
more information needed on how to reproduce this, 0 second voice messages do not reproduce it for me
