### ISSUE TITLE
android: dlopen fails for libgmp.so on LineageOS 18.1

### ISSUE THREAD

**Issue by attila-lendvai** [simplex-chat/simplex-chat#935]
it's on `lineage_vayu-userdebug 11 RQ3A.211001.001 eng.root.20220606.150112 dev-keys`, i.e. LineageOS 18.1 + microG; android 11.

the app fails to start. the relevant log is:

```
08-15 16:57:29.861 19049 21664 D SIMPLEX : starting server
08-15 16:57:29.861 19049 21664 D SIMPLEX : started server
08-15 16:57:29.865 19049 19049 D AndroidRuntime: Shutting down VM
08-15 16:57:29.865 19049 19049 E AndroidRuntime: FATAL EXCEPTION: main
08-15 16:57:29.865 19049 19049 E AndroidRuntime: Process: chat.simplex.app, PID: 19049
08-15 16:57:29.865 19049 19049 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgmp.so" not found: needed by /data/app/~~Dcjhnn6CgER1s-3r1EqV_A==/chat.simplex.app-1weR_M2BScEe6Ww9PrZTew==/base.apk!/lib/arm64-v8a/libsimplex.so in namespace classloader-namespace
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at chat.simplex.app.SimplexApp.<clinit>(SimplexApp.kt:111)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-15 16:57:29.865 19049 19049 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-15 16:57:29.871  1473 21665 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-15 16:57:29.871  1473  2791 W ActivityTaskManager:   Force finishing activity chat.simplex.app/.MainActivity_default
```

**Comment by attila-lendvai** [comment]
possible solution in [this comment](https://github.com/simplex-chat/simplex-chat/issues/136#issuecomment-984574604) that demonstrates static linking?

**Comment by epoberezkin** [comment]
Is this version downloaded from F-Droid main repo?

**Comment by attila-lendvai** [comment]
> Is this version downloaded from F-Droid main repo?

yes. i installed it from f-droid with a couple of clicks, i did nothing extra/unusual.

**Comment by epoberezkin** [comment]
the build in F-Droid is broken - it should be removed in a day or two - please use our F-Droid repo for now... Sorry about it.

https://github.com/simplex-chat/simplex-chat/issues/928

Closing this one
